### ISSUE TITLE
Don't hide panel & side menu on maximize

### ISSUE THREAD

**Issue by Vosjedev** [directvt/vtm#468]
Currently when you maximize a window it hides the panel and side menu. It would be usefull if vtm didn't hide them. Would it be technically possible to show them?

**Comment by o-sdn-o** [comment]
Of course it can be done. It also seems to me that we needlessly remove them when maximizing.

**Comment by Vosjedev** [comment]
Wow, that's a fast response. Of al devs I ever spoke to via github, you are by FAR the fastest...

**Comment by o-sdn-o** [comment]
We will have two modes
 - Fullscreen mode
 - Maximized window

Initially, full-screen mode was made to ensure maximum performance without heavy elements such as taskbar with acrylic and translucency. So, fullscreen mode will be the responsibility of the dtvt-application, since the application itself must provide the functionality (e.g. UI button, keyboard shortcut, or something else) for the user to toggle (or to return from) this mode.

When maximizing the window, the taskbar and panel should not be hidden. Maximization will be controlled by window controls.

**Comment by o-sdn-o** [comment]
I implemented it. You can test how it works. #470

**Comment by directvt** [comment]
I moved the repository from the netxs-group account to directvt. (since the name netxs-group doesn't mean anything). Some links may no longer work. These are temporary difficulties.

**Comment by o-sdn-o** [comment]
At first glance, window maximization works correctly. I closed this issue, but if something is wrong, please re-open it.

**Comment by o-sdn-o** [comment]
I would also like to add that I added a taskbar resizing grip due to the need for some space between the maximized window and the taskbar menu list. This indentation became the taskbar resizing grip.

**Comment by Vosjedev** [comment]
Works perfectly!
